network:
  version: 2
  renderer: networkd
  ethernets:
    myinterface:
      match:
        name: en*
      dhcp4: true
      dhcp-identifier: mac # means use mac address as dhcp id
      # else it will use /etc/machine-id, which would require using sys-prep
      # and adding back sshd keys... arg
